// Code generated by protoc-gen-gogo.
// source: gcm.proto
// DO NOT EDIT!

/*
Package proto_gcm is a generated protocol buffer package.

It is generated from these files:
	gcm.proto

It has these top-level messages:
	SendMessageRequest
	SendMessageResponse
*/
package proto_gcm

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type SendMessageRequest struct {
	RegistrationIds       []string `protobuf:"bytes,1,rep,name=registration_ids" json:"registration_ids,omitempty"`
	CollapseKey           *string  `protobuf:"bytes,2,opt,name=collapse_key" json:"collapse_key,omitempty"`
	Data                  *string  `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	DelayWhileIdle        *bool    `protobuf:"varint,4,opt,name=delay_while_idle" json:"delay_while_idle,omitempty"`
	TimeToLive            *uint64  `protobuf:"varint,5,opt,name=time_to_live" json:"time_to_live,omitempty"`
	RestrictedPackageName *string  `protobuf:"bytes,6,opt,name=restricted_package_name" json:"restricted_package_name,omitempty"`
	DryRun                *bool    `protobuf:"varint,7,opt,name=dry_run" json:"dry_run,omitempty"`
	XXX_unrecognized      []byte   `json:"-"`
}

func (m *SendMessageRequest) Reset()         { *m = SendMessageRequest{} }
func (m *SendMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageRequest) ProtoMessage()    {}

func (m *SendMessageRequest) GetRegistrationIds() []string {
	if m != nil {
		return m.RegistrationIds
	}
	return nil
}

func (m *SendMessageRequest) GetCollapseKey() string {
	if m != nil && m.CollapseKey != nil {
		return *m.CollapseKey
	}
	return ""
}

func (m *SendMessageRequest) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

func (m *SendMessageRequest) GetDelayWhileIdle() bool {
	if m != nil && m.DelayWhileIdle != nil {
		return *m.DelayWhileIdle
	}
	return false
}

func (m *SendMessageRequest) GetTimeToLive() uint64 {
	if m != nil && m.TimeToLive != nil {
		return *m.TimeToLive
	}
	return 0
}

func (m *SendMessageRequest) GetRestrictedPackageName() string {
	if m != nil && m.RestrictedPackageName != nil {
		return *m.RestrictedPackageName
	}
	return ""
}

func (m *SendMessageRequest) GetDryRun() bool {
	if m != nil && m.DryRun != nil {
		return *m.DryRun
	}
	return false
}

type SendMessageResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SendMessageResponse) Reset()         { *m = SendMessageResponse{} }
func (m *SendMessageResponse) String() string { return proto.CompactTextString(m) }
func (*SendMessageResponse) ProtoMessage()    {}

func init() {
}
