// Code generated by protoc-gen-gogo.
// source: lobby.proto
// DO NOT EDIT!

/*
Package proto_lobby is a generated protocol buffer package.

It is generated from these files:
	lobby.proto

It has these top-level messages:
	Player
	Room
	RoomOptions
	CreateRoomRequest
	CreateRoomResponse
	JoinRoomRequest
	JoinRoomResponse
	ListRoomsRequest
	ListRoomsResponse
*/
package proto_lobby

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type CreateRoomResponse_ErrorCode int32

const (
	CreateRoomResponse_ALREADY_JOINED CreateRoomResponse_ErrorCode = 0
)

var CreateRoomResponse_ErrorCode_name = map[int32]string{
	0: "ALREADY_JOINED",
}
var CreateRoomResponse_ErrorCode_value = map[string]int32{
	"ALREADY_JOINED": 0,
}

func (x CreateRoomResponse_ErrorCode) Enum() *CreateRoomResponse_ErrorCode {
	p := new(CreateRoomResponse_ErrorCode)
	*p = x
	return p
}
func (x CreateRoomResponse_ErrorCode) String() string {
	return proto.EnumName(CreateRoomResponse_ErrorCode_name, int32(x))
}
func (x *CreateRoomResponse_ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CreateRoomResponse_ErrorCode_value, data, "CreateRoomResponse_ErrorCode")
	if err != nil {
		return err
	}
	*x = CreateRoomResponse_ErrorCode(value)
	return nil
}

type Player struct {
	UserId           *uint64 `protobuf:"varint,1,req,name=user_id" json:"user_id,omitempty"`
	Nickname         *string `protobuf:"bytes,2,req,name=nickname" json:"nickname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}

func (m *Player) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *Player) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

type Room struct {
	Id               *string      `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Name             *string      `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Options          *RoomOptions `protobuf:"bytes,3,req,name=options" json:"options,omitempty"`
	Owner            *Player      `protobuf:"bytes,4,req,name=owner" json:"owner,omitempty"`
	Players          []*Player    `protobuf:"bytes,5,rep,name=players" json:"players,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}

func (m *Room) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Room) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Room) GetOptions() *RoomOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Room) GetOwner() *Player {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *Room) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

type RoomOptions struct {
	Private          *bool   `protobuf:"varint,1,opt,name=private,def=0" json:"private,omitempty"`
	Password         *string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Autostart        *bool   `protobuf:"varint,3,opt,name=autostart,def=0" json:"autostart,omitempty"`
	FillBots         *bool   `protobuf:"varint,4,opt,name=fill_bots,def=1" json:"fill_bots,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RoomOptions) Reset()         { *m = RoomOptions{} }
func (m *RoomOptions) String() string { return proto.CompactTextString(m) }
func (*RoomOptions) ProtoMessage()    {}

const Default_RoomOptions_Private bool = false
const Default_RoomOptions_Autostart bool = false
const Default_RoomOptions_FillBots bool = true

func (m *RoomOptions) GetPrivate() bool {
	if m != nil && m.Private != nil {
		return *m.Private
	}
	return Default_RoomOptions_Private
}

func (m *RoomOptions) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *RoomOptions) GetAutostart() bool {
	if m != nil && m.Autostart != nil {
		return *m.Autostart
	}
	return Default_RoomOptions_Autostart
}

func (m *RoomOptions) GetFillBots() bool {
	if m != nil && m.FillBots != nil {
		return *m.FillBots
	}
	return Default_RoomOptions_FillBots
}

// Requires proto_headers.AuthorizationHeader to be sent as header.
type CreateRoomRequest struct {
	Name             *string      `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Options          *RoomOptions `protobuf:"bytes,2,req,name=options" json:"options,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *CreateRoomRequest) Reset()         { *m = CreateRoomRequest{} }
func (m *CreateRoomRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRoomRequest) ProtoMessage()    {}

func (m *CreateRoomRequest) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CreateRoomRequest) GetOptions() *RoomOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type CreateRoomResponse struct {
	Error            *CreateRoomResponse_Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Room             *Room                     `protobuf:"bytes,2,opt,name=room" json:"room,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *CreateRoomResponse) Reset()         { *m = CreateRoomResponse{} }
func (m *CreateRoomResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRoomResponse) ProtoMessage()    {}

func (m *CreateRoomResponse) GetError() *CreateRoomResponse_Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *CreateRoomResponse) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

type CreateRoomResponse_Error struct {
	Error            *CreateRoomResponse_ErrorCode `protobuf:"varint,1,req,name=error,enum=proto_lobby.CreateRoomResponse_ErrorCode" json:"error,omitempty"`
	Description      *string                       `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *CreateRoomResponse_Error) Reset()         { *m = CreateRoomResponse_Error{} }
func (m *CreateRoomResponse_Error) String() string { return proto.CompactTextString(m) }
func (*CreateRoomResponse_Error) ProtoMessage()    {}

func (m *CreateRoomResponse_Error) GetError() CreateRoomResponse_ErrorCode {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return CreateRoomResponse_ALREADY_JOINED
}

func (m *CreateRoomResponse_Error) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

type JoinRoomRequest struct {
	RoomId           *string `protobuf:"bytes,1,req,name=room_id" json:"room_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *JoinRoomRequest) Reset()         { *m = JoinRoomRequest{} }
func (m *JoinRoomRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRoomRequest) ProtoMessage()    {}

func (m *JoinRoomRequest) GetRoomId() string {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return ""
}

type JoinRoomResponse struct {
	Room             *Room  `protobuf:"bytes,1,opt,name=room" json:"room,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *JoinRoomResponse) Reset()         { *m = JoinRoomResponse{} }
func (m *JoinRoomResponse) String() string { return proto.CompactTextString(m) }
func (*JoinRoomResponse) ProtoMessage()    {}

func (m *JoinRoomResponse) GetRoom() *Room {
	if m != nil {
		return m.Room
	}
	return nil
}

type ListRoomsRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ListRoomsRequest) Reset()         { *m = ListRoomsRequest{} }
func (m *ListRoomsRequest) String() string { return proto.CompactTextString(m) }
func (*ListRoomsRequest) ProtoMessage()    {}

type ListRoomsResponse struct {
	Rooms            []*Room `protobuf:"bytes,1,rep,name=rooms" json:"rooms,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ListRoomsResponse) Reset()         { *m = ListRoomsResponse{} }
func (m *ListRoomsResponse) String() string { return proto.CompactTextString(m) }
func (*ListRoomsResponse) ProtoMessage()    {}

func (m *ListRoomsResponse) GetRooms() []*Room {
	if m != nil {
		return m.Rooms
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto_lobby.CreateRoomResponse_ErrorCode", CreateRoomResponse_ErrorCode_name, CreateRoomResponse_ErrorCode_value)
}
