// Code generated by protoc-gen-gogo.
// source: presence.proto
// DO NOT EDIT!

/*
Package proto_presence is a generated protocol buffer package.

It is generated from these files:
	presence.proto

It has these top-level messages:
	Device
	UpdateUserStatusRequest
	UpdateUserStatusResponse
	GetUserDevicesRequest
	GetUserDevicesResponse
*/
package proto_presence

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Device_Type int32

const (
	Device_ANDROID_GCM Device_Type = 0
)

var Device_Type_name = map[int32]string{
	0: "ANDROID_GCM",
}
var Device_Type_value = map[string]int32{
	"ANDROID_GCM": 0,
}

func (x Device_Type) Enum() *Device_Type {
	p := new(Device_Type)
	*p = x
	return p
}
func (x Device_Type) String() string {
	return proto.EnumName(Device_Type_name, int32(x))
}
func (x *Device_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Device_Type_value, data, "Device_Type")
	if err != nil {
		return err
	}
	*x = Device_Type(value)
	return nil
}

type UpdateUserStatusRequest_Status int32

const (
	UpdateUserStatusRequest_OFFLINE UpdateUserStatusRequest_Status = 1
	UpdateUserStatusRequest_ONLINE  UpdateUserStatusRequest_Status = 2
)

var UpdateUserStatusRequest_Status_name = map[int32]string{
	1: "OFFLINE",
	2: "ONLINE",
}
var UpdateUserStatusRequest_Status_value = map[string]int32{
	"OFFLINE": 1,
	"ONLINE":  2,
}

func (x UpdateUserStatusRequest_Status) Enum() *UpdateUserStatusRequest_Status {
	p := new(UpdateUserStatusRequest_Status)
	*p = x
	return p
}
func (x UpdateUserStatusRequest_Status) String() string {
	return proto.EnumName(UpdateUserStatusRequest_Status_name, int32(x))
}
func (x *UpdateUserStatusRequest_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UpdateUserStatusRequest_Status_value, data, "UpdateUserStatusRequest_Status")
	if err != nil {
		return err
	}
	*x = UpdateUserStatusRequest_Status(value)
	return nil
}

type Device struct {
	Type *Device_Type `protobuf:"varint,1,req,name=type,enum=proto_presence.Device_Type" json:"type,omitempty"`
	// Android GCM fields
	GcmRegistrationId *string `protobuf:"bytes,2,opt,name=gcm_registration_id" json:"gcm_registration_id,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}

func (m *Device) GetType() Device_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Device_ANDROID_GCM
}

func (m *Device) GetGcmRegistrationId() string {
	if m != nil && m.GcmRegistrationId != nil {
		return *m.GcmRegistrationId
	}
	return ""
}

type UpdateUserStatusRequest struct {
	UserId           *string                         `protobuf:"bytes,1,req,name=user_id" json:"user_id,omitempty"`
	Status           *UpdateUserStatusRequest_Status `protobuf:"varint,2,opt,name=status,enum=proto_presence.UpdateUserStatusRequest_Status" json:"status,omitempty"`
	Device           *Device                         `protobuf:"bytes,3,opt,name=device" json:"device,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *UpdateUserStatusRequest) Reset()         { *m = UpdateUserStatusRequest{} }
func (m *UpdateUserStatusRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserStatusRequest) ProtoMessage()    {}

func (m *UpdateUserStatusRequest) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *UpdateUserStatusRequest) GetStatus() UpdateUserStatusRequest_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return UpdateUserStatusRequest_OFFLINE
}

func (m *UpdateUserStatusRequest) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

type UpdateUserStatusResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *UpdateUserStatusResponse) Reset()         { *m = UpdateUserStatusResponse{} }
func (m *UpdateUserStatusResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserStatusResponse) ProtoMessage()    {}

type GetUserDevicesRequest struct {
	UserId           *string `protobuf:"bytes,1,req,name=user_id" json:"user_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetUserDevicesRequest) Reset()         { *m = GetUserDevicesRequest{} }
func (m *GetUserDevicesRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserDevicesRequest) ProtoMessage()    {}

func (m *GetUserDevicesRequest) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

type GetUserDevicesResponse struct {
	Devices          []*Device `protobuf:"bytes,1,rep,name=devices" json:"devices,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *GetUserDevicesResponse) Reset()         { *m = GetUserDevicesResponse{} }
func (m *GetUserDevicesResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserDevicesResponse) ProtoMessage()    {}

func (m *GetUserDevicesResponse) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto_presence.Device_Type", Device_Type_name, Device_Type_value)
	proto.RegisterEnum("proto_presence.UpdateUserStatusRequest_Status", UpdateUserStatusRequest_Status_name, UpdateUserStatusRequest_Status_value)
}
