// Code generated by protoc-gen-gogo.
// source: notify.proto
// DO NOT EDIT!

/*
Package proto_notify is a generated protocol buffer package.

It is generated from these files:
	notify.proto

It has these top-level messages:
	MessageUsersHeader
	MessageUsersResponse
*/
package proto_notify

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type MessageUsersHeader struct {
	UserIds          []uint64 `protobuf:"varint,1,rep,name=user_ids" json:"user_ids,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MessageUsersHeader) Reset()         { *m = MessageUsersHeader{} }
func (m *MessageUsersHeader) String() string { return proto.CompactTextString(m) }
func (*MessageUsersHeader) ProtoMessage()    {}

func (m *MessageUsersHeader) GetUserIds() []uint64 {
	if m != nil {
		return m.UserIds
	}
	return nil
}

type MessageUsersResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MessageUsersResponse) Reset()         { *m = MessageUsersResponse{} }
func (m *MessageUsersResponse) String() string { return proto.CompactTextString(m) }
func (*MessageUsersResponse) ProtoMessage()    {}

func init() {
}
