// Code generated by protoc-gen-gogo.
// source: msghandler.proto
// DO NOT EDIT!

/*
Package proto_msghandler is a generated protocol buffer package.

It is generated from these files:
	msghandler.proto

It has these top-level messages:
	RouteMessageRequest
	RouteMessageResponse
*/
package proto_msghandler

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type RouteMessageRequest struct {
	Data             *string `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RouteMessageRequest) Reset()         { *m = RouteMessageRequest{} }
func (m *RouteMessageRequest) String() string { return proto.CompactTextString(m) }
func (*RouteMessageRequest) ProtoMessage()    {}

func (m *RouteMessageRequest) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

type RouteMessageResponse struct {
	Data             *string `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RouteMessageResponse) Reset()         { *m = RouteMessageResponse{} }
func (m *RouteMessageResponse) String() string { return proto.CompactTextString(m) }
func (*RouteMessageResponse) ProtoMessage()    {}

func (m *RouteMessageResponse) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

func init() {
}
