// Code generated by protoc-gen-gogo.
// source: errors.proto
// DO NOT EDIT!

/*
Package proto_errors is a generated protocol buffer package.

It is generated from these files:
	errors.proto

It has these top-level messages:
	ErrorResponse
*/
package proto_errors

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Error int32

const (
	Error_INTERNAL_ERROR      Error = 0
	Error_MISSING_HEADER      Error = 1
	Error_UNSUPPORTED_MESSAGE Error = 2
	Error_MALFORMED_MESSAGE   Error = 3
	Error_EMPTY_MESSAGE       Error = 4
)

var Error_name = map[int32]string{
	0: "INTERNAL_ERROR",
	1: "MISSING_HEADER",
	2: "UNSUPPORTED_MESSAGE",
	3: "MALFORMED_MESSAGE",
	4: "EMPTY_MESSAGE",
}
var Error_value = map[string]int32{
	"INTERNAL_ERROR":      0,
	"MISSING_HEADER":      1,
	"UNSUPPORTED_MESSAGE": 2,
	"MALFORMED_MESSAGE":   3,
	"EMPTY_MESSAGE":       4,
}

func (x Error) Enum() *Error {
	p := new(Error)
	*p = x
	return p
}
func (x Error) String() string {
	return proto.EnumName(Error_name, int32(x))
}
func (x *Error) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Error_value, data, "Error")
	if err != nil {
		return err
	}
	*x = Error(value)
	return nil
}

type ErrorResponse struct {
	Error            *Error  `protobuf:"varint,1,req,name=error,enum=proto_errors.Error" json:"error,omitempty"`
	Description      *string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}

func (m *ErrorResponse) GetError() Error {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return Error_INTERNAL_ERROR
}

func (m *ErrorResponse) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto_errors.Error", Error_name, Error_value)
}
