// Code generated by protoc-gen-gogo.
// source: errors.proto
// DO NOT EDIT!

/*
Package proto_errors is a generated protocol buffer package.

It is generated from these files:
	errors.proto

It has these top-level messages:
	ErrorResponse
*/
package proto_errors

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type ErrorCode int32

const (
	ErrorCode_INTERNAL_ERROR      ErrorCode = 0
	ErrorCode_MISSING_HEADER      ErrorCode = 1
	ErrorCode_UNSUPPORTED_MESSAGE ErrorCode = 2
	ErrorCode_MALFORMED_MESSAGE   ErrorCode = 3
	ErrorCode_EMPTY_MESSAGE       ErrorCode = 4
	ErrorCode_MISSING_FIELD       ErrorCode = 5
)

var ErrorCode_name = map[int32]string{
	0: "INTERNAL_ERROR",
	1: "MISSING_HEADER",
	2: "UNSUPPORTED_MESSAGE",
	3: "MALFORMED_MESSAGE",
	4: "EMPTY_MESSAGE",
	5: "MISSING_FIELD",
}
var ErrorCode_value = map[string]int32{
	"INTERNAL_ERROR":      0,
	"MISSING_HEADER":      1,
	"UNSUPPORTED_MESSAGE": 2,
	"MALFORMED_MESSAGE":   3,
	"EMPTY_MESSAGE":       4,
	"MISSING_FIELD":       5,
}

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}
func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (x *ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ErrorCode_value, data, "ErrorCode")
	if err != nil {
		return err
	}
	*x = ErrorCode(value)
	return nil
}

type ErrorResponse struct {
	ErrorCode        *ErrorCode `protobuf:"varint,1,req,name=error_code,enum=proto_errors.ErrorCode" json:"error_code,omitempty"`
	Description      *string    `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}

func (m *ErrorResponse) GetErrorCode() ErrorCode {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return ErrorCode_INTERNAL_ERROR
}

func (m *ErrorResponse) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto_errors.ErrorCode", ErrorCode_name, ErrorCode_value)
}
