// Code generated by protoc-gen-gogo.
// source: oauth2.proto
// DO NOT EDIT!

/*
Package proto_oauth2 is a generated protocol buffer package.

It is generated from these files:
	oauth2.proto

It has these top-level messages:
	AuthorizationRequest
	AuthorizationResponse
	Client
	AccessTokenAuthentication
	AccessTokenRequest
	AccessTokenResponse
	AccessToken
	ErrorResponse
*/
package proto_oauth2

import proto "code.google.com/p/gogoprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type AuthorizationRequest struct {
	ResponseType     *string `protobuf:"bytes,1,req,name=response_type" json:"response_type,omitempty"`
	Scope            *string `protobuf:"bytes,2,opt,name=scope" json:"scope,omitempty"`
	State            *string `protobuf:"bytes,3,opt,name=state" json:"state,omitempty"`
	ClientId         *string `protobuf:"bytes,4,opt,name=client_id" json:"client_id,omitempty"`
	RedirectUri      *string `protobuf:"bytes,5,opt,name=redirect_uri" json:"redirect_uri,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AuthorizationRequest) Reset()         { *m = AuthorizationRequest{} }
func (m *AuthorizationRequest) String() string { return proto.CompactTextString(m) }
func (*AuthorizationRequest) ProtoMessage()    {}

func (m *AuthorizationRequest) GetResponseType() string {
	if m != nil && m.ResponseType != nil {
		return *m.ResponseType
	}
	return ""
}

func (m *AuthorizationRequest) GetScope() string {
	if m != nil && m.Scope != nil {
		return *m.Scope
	}
	return ""
}

func (m *AuthorizationRequest) GetState() string {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ""
}

func (m *AuthorizationRequest) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *AuthorizationRequest) GetRedirectUri() string {
	if m != nil && m.RedirectUri != nil {
		return *m.RedirectUri
	}
	return ""
}

type AuthorizationResponse struct {
	Code             *string `protobuf:"bytes,1,req,name=code" json:"code,omitempty"`
	State            *string `protobuf:"bytes,2,req,name=state" json:"state,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AuthorizationResponse) Reset()         { *m = AuthorizationResponse{} }
func (m *AuthorizationResponse) String() string { return proto.CompactTextString(m) }
func (*AuthorizationResponse) ProtoMessage()    {}

func (m *AuthorizationResponse) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *AuthorizationResponse) GetState() string {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ""
}

type Client struct {
	Id               *string `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Secret           *string `protobuf:"bytes,2,opt,name=secret" json:"secret,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}

func (m *Client) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Client) GetSecret() string {
	if m != nil && m.Secret != nil {
		return *m.Secret
	}
	return ""
}

type AccessTokenAuthentication struct {
	Client           *Client             `protobuf:"bytes,1,req,name=client" json:"client,omitempty"`
	Request          *AccessTokenRequest `protobuf:"bytes,2,req,name=request" json:"request,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *AccessTokenAuthentication) Reset()         { *m = AccessTokenAuthentication{} }
func (m *AccessTokenAuthentication) String() string { return proto.CompactTextString(m) }
func (*AccessTokenAuthentication) ProtoMessage()    {}

func (m *AccessTokenAuthentication) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *AccessTokenAuthentication) GetRequest() *AccessTokenRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

type AccessTokenRequest struct {
	GrantType *string `protobuf:"bytes,1,req,name=grant_type" json:"grant_type,omitempty"`
	Scope     *string `protobuf:"bytes,2,opt,name=scope" json:"scope,omitempty"`
	// Authorization Code Grant
	Code        *string `protobuf:"bytes,3,opt,name=code" json:"code,omitempty"`
	RedirectUri *string `protobuf:"bytes,4,opt,name=redirect_uri" json:"redirect_uri,omitempty"`
	ClientId    *string `protobuf:"bytes,5,opt,name=client_id" json:"client_id,omitempty"`
	// Resource Owner Password Credentials Grant
	Username *string `protobuf:"bytes,6,opt,name=username" json:"username,omitempty"`
	Password *string `protobuf:"bytes,7,opt,name=password" json:"password,omitempty"`
	// Refreshing token
	RefreshToken     *string `protobuf:"bytes,8,opt,name=refresh_token" json:"refresh_token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AccessTokenRequest) Reset()         { *m = AccessTokenRequest{} }
func (m *AccessTokenRequest) String() string { return proto.CompactTextString(m) }
func (*AccessTokenRequest) ProtoMessage()    {}

func (m *AccessTokenRequest) GetGrantType() string {
	if m != nil && m.GrantType != nil {
		return *m.GrantType
	}
	return ""
}

func (m *AccessTokenRequest) GetScope() string {
	if m != nil && m.Scope != nil {
		return *m.Scope
	}
	return ""
}

func (m *AccessTokenRequest) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *AccessTokenRequest) GetRedirectUri() string {
	if m != nil && m.RedirectUri != nil {
		return *m.RedirectUri
	}
	return ""
}

func (m *AccessTokenRequest) GetClientId() string {
	if m != nil && m.ClientId != nil {
		return *m.ClientId
	}
	return ""
}

func (m *AccessTokenRequest) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *AccessTokenRequest) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *AccessTokenRequest) GetRefreshToken() string {
	if m != nil && m.RefreshToken != nil {
		return *m.RefreshToken
	}
	return ""
}

type AccessTokenResponse struct {
	Success          *bool          `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Token            *AccessToken   `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	Error            *ErrorResponse `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *AccessTokenResponse) Reset()         { *m = AccessTokenResponse{} }
func (m *AccessTokenResponse) String() string { return proto.CompactTextString(m) }
func (*AccessTokenResponse) ProtoMessage()    {}

func (m *AccessTokenResponse) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *AccessTokenResponse) GetToken() *AccessToken {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *AccessTokenResponse) GetError() *ErrorResponse {
	if m != nil {
		return m.Error
	}
	return nil
}

type AccessToken struct {
	AccessToken      *string `protobuf:"bytes,1,req,name=access_token" json:"access_token,omitempty"`
	TokenType        *string `protobuf:"bytes,2,req,name=token_type" json:"token_type,omitempty"`
	ExpiresIn        *uint64 `protobuf:"varint,3,opt,name=expires_in" json:"expires_in,omitempty"`
	RefreshToken     *string `protobuf:"bytes,4,opt,name=refresh_token" json:"refresh_token,omitempty"`
	Scope            *string `protobuf:"bytes,5,opt,name=scope" json:"scope,omitempty"`
	State            *string `protobuf:"bytes,6,opt,name=state" json:"state,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AccessToken) Reset()         { *m = AccessToken{} }
func (m *AccessToken) String() string { return proto.CompactTextString(m) }
func (*AccessToken) ProtoMessage()    {}

func (m *AccessToken) GetAccessToken() string {
	if m != nil && m.AccessToken != nil {
		return *m.AccessToken
	}
	return ""
}

func (m *AccessToken) GetTokenType() string {
	if m != nil && m.TokenType != nil {
		return *m.TokenType
	}
	return ""
}

func (m *AccessToken) GetExpiresIn() uint64 {
	if m != nil && m.ExpiresIn != nil {
		return *m.ExpiresIn
	}
	return 0
}

func (m *AccessToken) GetRefreshToken() string {
	if m != nil && m.RefreshToken != nil {
		return *m.RefreshToken
	}
	return ""
}

func (m *AccessToken) GetScope() string {
	if m != nil && m.Scope != nil {
		return *m.Scope
	}
	return ""
}

func (m *AccessToken) GetState() string {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ""
}

type ErrorResponse struct {
	Error            *string `protobuf:"bytes,1,req,name=error" json:"error,omitempty"`
	ErrorDescription *string `protobuf:"bytes,2,opt,name=error_description" json:"error_description,omitempty"`
	ErrorUri         *string `protobuf:"bytes,3,opt,name=error_uri" json:"error_uri,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ErrorResponse) Reset()         { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()    {}

func (m *ErrorResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *ErrorResponse) GetErrorDescription() string {
	if m != nil && m.ErrorDescription != nil {
		return *m.ErrorDescription
	}
	return ""
}

func (m *ErrorResponse) GetErrorUri() string {
	if m != nil && m.ErrorUri != nil {
		return *m.ErrorUri
	}
	return ""
}

func init() {
}
